/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/account/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Account */
        get: operations["list_account_account__get"];
        put?: never;
        /** Create Account */
        post: operations["create_account_account__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/{account_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Account */
        get: operations["retrieve_account_account__account_id___get"];
        /** Update Account */
        put: operations["update_account_account__account_id___put"];
        post?: never;
        /** Delete Account */
        delete: operations["delete_account_account__account_id___delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/options/account/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Account Option */
        get: operations["list_account_option_options_account__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/{account_id}/balance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Account Balance */
        put: operations["update_account_balance_account__account_id__balance__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Account */
        Account: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
            /** Number */
            number: string;
            account_type: components["schemas"]["AccountType"] | null;
            /** Balance */
            balance: string;
            /** Account Number */
            account_number: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Modified At
             * Format: date-time
             */
            last_modified_at: string;
            created_by: components["schemas"]["UserMin"];
            last_modified_by: components["schemas"]["UserMin"] | null;
            parent: components["schemas"]["AccountMin"] | null;
            currency: components["schemas"]["CurrencyMin"];
            /** Level */
            level: number;
        };
        /** AccountBalanceUpdate */
        AccountBalanceUpdate: {
            /** Balance */
            balance: number | string;
        };
        /** AccountCreate */
        AccountCreate: {
            /** Name */
            name: string;
            /** Number */
            number: string;
            account_type: components["schemas"]["AccountType"] | null;
            /** Parent Id */
            parent_id: number | null;
            /** Currency Id */
            currency_id: number;
        };
        /** AccountMin */
        AccountMin: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
            /** Number */
            number: string;
            account_type: components["schemas"]["AccountType"] | null;
            /** Account Number */
            account_number: string;
        };
        /** AccountOpt */
        AccountOpt: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
            /** Number */
            number: string;
            account_type: components["schemas"]["AccountType"] | null;
            /** Account Number */
            account_number: string;
        };
        /**
         * AccountType
         * @enum {string}
         */
        AccountType: "Asset" | "Liability" | "Equity" | "Revenue" | "Expense";
        /** AccountUpdate */
        AccountUpdate: {
            /** Name */
            name: string;
            /** Number */
            number: string;
            account_type: components["schemas"]["AccountType"] | null;
            /** Parent Id */
            parent_id: number | null;
            /** Currency Id */
            currency_id: number;
        };
        /** CurrencyMin */
        CurrencyMin: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
            /** Iso */
            iso: string;
            /** Symbol */
            symbol: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PaginatedAccount */
        PaginatedAccount: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["Account"][];
        };
        /** PaginatedAccountOpt */
        PaginatedAccountOpt: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["AccountOpt"][];
        };
        /** UserImageURL */
        UserImageURL: {
            /** Url */
            url: string | null;
        };
        /** UserMin */
        UserMin: {
            /** Pk */
            pk: number;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            image: components["schemas"]["UserImageURL"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_account_account__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAccount"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_account_account__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_account_account__account_id___get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_account__account_id___put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_account__account_id___delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_account_option_options_account__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAccountOpt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_balance_account__account_id__balance__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountBalanceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
