/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/contact/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contact */
        get: operations["list_contact_contact__get"];
        put?: never;
        /** Create Contact */
        post: operations["create_contact_contact__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contact/{contact_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Contact */
        get: operations["retrieve_contact_contact__contact_id___get"];
        /** Update Contact */
        put: operations["update_contact_contact__contact_id___put"];
        post?: never;
        /** Delete Contact */
        delete: operations["delete_contact_contact__contact_id___delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/options/contact/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contact Option */
        get: operations["list_contact_option_options_contact__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contact/{contact_id}/soft_delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft Delete Contact */
        delete: operations["soft_delete_contact_contact__contact_id__soft_delete_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contact/{contact_id}/image/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload Contact Image */
        put: operations["upload_contact_image_contact__contact_id__image__put"];
        post?: never;
        /** Delete Contact Image */
        delete: operations["delete_contact_image_contact__contact_id__image__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contact_upload_template/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Contact Upload Template */
        get: operations["download_contact_upload_template_contact_upload_template__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contact_upload/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contact Upload */
        get: operations["list_contact_upload_contact_upload__get"];
        put?: never;
        /** Upload Contact */
        post: operations["upload_contact_contact_upload__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contact_upload/{upload_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Contact Upload */
        get: operations["retrieve_contact_upload_contact_upload__upload_id___get"];
        put?: never;
        post?: never;
        /** Delete Contact Upload */
        delete: operations["delete_contact_upload_contact_upload__upload_id___delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contact_upload/{upload_id}/data_error/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contact Upload Data Error */
        get: operations["list_contact_upload_data_error_contact_upload__upload_id__data_error__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/industry/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Industry */
        get: operations["list_industry_industry__get"];
        put?: never;
        /** Create Industry */
        post: operations["create_industry_industry__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/industry/{industry_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Industry */
        get: operations["retrieve_industry_industry__industry_id___get"];
        /** Update Industry */
        put: operations["update_industry_industry__industry_id___put"];
        post?: never;
        /** Delete Industry */
        delete: operations["delete_industry_industry__industry_id___delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/options/industry/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Industry Option */
        get: operations["list_industry_option_options_industry__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/address/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Address */
        get: operations["list_address_address__get"];
        put?: never;
        /** Create Address */
        post: operations["create_address_address__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/address/{address_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Address */
        get: operations["retrieve_address_address__address_id___get"];
        /** Update Address */
        put: operations["update_address_address__address_id___put"];
        post?: never;
        /** Delete Address */
        delete: operations["delete_address_address__address_id___delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/options/address/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Address Option */
        get: operations["list_address_option_options_address__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/country/{country_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Country */
        get: operations["retrieve_country_country__country_id___get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/country/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Country */
        get: operations["list_country_country__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/options/country/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Country Option */
        get: operations["list_country_option_options_country__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/currency/{currency_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Currency */
        get: operations["retrieve_currency_currency__currency_id___get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/currency/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Currency */
        get: operations["list_currency_currency__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/options/currency/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Currency Option */
        get: operations["list_currency_option_options_currency__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/phonecode/{phonecode_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Phonecode */
        get: operations["retrieve_phonecode_phonecode__phonecode_id___get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/phonecode/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Phonecode */
        get: operations["list_phonecode_phonecode__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/options/phonecode/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Phonecode Option */
        get: operations["list_phonecode_option_options_phonecode__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vat/{vat_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Vat */
        get: operations["retrieve_vat_vat__vat_id___get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vat/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vat */
        get: operations["list_vat_vat__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/options/vat/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vat Option */
        get: operations["list_vat_option_options_vat__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tag/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tag */
        get: operations["list_tag_tag__get"];
        put?: never;
        /** Create Tag */
        post: operations["create_tag_tag__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/options/tag/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tag Option */
        get: operations["list_tag_option_options_tag__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tag/{tag_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Tag */
        put: operations["update_tag_tag__tag_id___put"];
        post?: never;
        /** Delete Tag */
        delete: operations["delete_tag_tag__tag_id___delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Address */
        Address: {
            /** Pk */
            pk: number;
            address_type: components["schemas"]["AddressType"];
            /** Name */
            name: string | null;
            /** Email */
            email: string | null;
            /** Address */
            address: string;
            /** Phone */
            phone: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Modified At
             * Format: date-time
             */
            last_modified_at: string;
            created_by: components["schemas"]["UserMin"];
            last_modified_by: components["schemas"]["UserMin"] | null;
            contact: components["schemas"]["ContactMin"];
        };
        /** AddressCreate */
        AddressCreate: {
            address_type: components["schemas"]["AddressType"];
            /** Name */
            name: string | null;
            /** Email */
            email: string | null;
            /** Address */
            address: string;
            /** Phone */
            phone: string | null;
            /** Contact Id */
            contact_id: number;
        };
        /** AddressOpt */
        AddressOpt: {
            /** Pk */
            pk: number;
            address_type: components["schemas"]["AddressType"];
            /** Name */
            name: string | null;
            /** Email */
            email: string | null;
            /** Address */
            address: string;
            /** Phone */
            phone: string | null;
        };
        /**
         * AddressType
         * @enum {string}
         */
        AddressType: "Main" | "Billing" | "Shipping" | "Other";
        /** AddressUpdate */
        AddressUpdate: {
            address_type: components["schemas"]["AddressType"];
            /** Name */
            name: string | null;
            /** Email */
            email: string | null;
            /** Address */
            address: string;
            /** Phone */
            phone: string | null;
        };
        /** Body_upload_contact_contact_upload__post */
        Body_upload_contact_contact_upload__post: {
            /**
             * Upload
             * Format: binary
             */
            upload: string;
        };
        /** Body_upload_contact_image_contact__contact_id__image__put */
        Body_upload_contact_image_contact__contact_id__image__put: {
            /**
             * Upload
             * Format: binary
             */
            upload: string;
        };
        /** Contact */
        Contact: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
            legal_type: components["schemas"]["ContactLegalType"];
            /** Tax Id */
            tax_id: string | null;
            image: components["schemas"]["ContactImageURL"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Modified At
             * Format: date-time
             */
            last_modified_at: string;
            created_by: components["schemas"]["UserMin"];
            last_modified_by: components["schemas"]["UserMin"] | null;
            /** Deleted At */
            deleted_at: string | null;
            parent: components["schemas"]["ContactMin"] | null;
            /** Tags */
            tags: components["schemas"]["TagMin"][];
        };
        /** ContactCreate */
        ContactCreate: {
            /** Name */
            name: string;
            legal_type: components["schemas"]["ContactLegalType"];
            /** Tax Id */
            tax_id: string | null;
            /** Parent Id */
            parent_id: number | null;
            /** Tags */
            tags: number[];
        };
        /** ContactImageURL */
        ContactImageURL: {
            /** Url */
            url: string | null;
        };
        /**
         * ContactLegalType
         * @enum {string}
         */
        ContactLegalType: "Individual" | "Partnership" | "Limited Partnership" | "Limited Liability Partnership" | "Limited Liability Company" | "Public Limited Company" | "Private Limited Company" | "Corporation" | "Nonprofit Organization" | "Cooperative" | "Trust" | "Government Agency";
        /** ContactMin */
        ContactMin: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
            legal_type: components["schemas"]["ContactLegalType"];
            image: components["schemas"]["ContactImageURL"];
            parent: components["schemas"]["ContactMin"] | null;
        };
        /** ContactOpt */
        ContactOpt: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
            legal_type: components["schemas"]["ContactLegalType"];
            image: components["schemas"]["ContactImageURL"];
            parent: components["schemas"]["ContactMin"] | null;
        };
        /** ContactUpdate */
        ContactUpdate: {
            /** Name */
            name: string;
            legal_type: components["schemas"]["ContactLegalType"];
            /** Tax Id */
            tax_id: string | null;
            /** Parent Id */
            parent_id: number | null;
            /** Tags */
            tags: number[];
        };
        /** Country */
        Country: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
            /** Iso A2 */
            iso_a2: string;
            /** Iso A3 */
            iso_a3: string;
            /** Iso N */
            iso_n: number;
        };
        /** CountryOpt */
        CountryOpt: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
            /** Iso A2 */
            iso_a2: string;
            /** Iso A3 */
            iso_a3: string;
            /** Iso N */
            iso_n: number;
        };
        /** Currency */
        Currency: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
            /** Iso */
            iso: string;
            /** Symbol */
            symbol: string | null;
            country: components["schemas"]["Country"] | null;
        };
        /** CurrencyOpt */
        CurrencyOpt: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
            /** Iso */
            iso: string;
            /** Symbol */
            symbol: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Industry */
        Industry: {
            /** Pk */
            pk: number;
            industry_type: components["schemas"]["IndustryType"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Modified At
             * Format: date-time
             */
            last_modified_at: string;
            created_by: components["schemas"]["UserMin"];
            last_modified_by: components["schemas"]["UserMin"] | null;
            contact: components["schemas"]["ContactMin"];
        };
        /** IndustryCreate */
        IndustryCreate: {
            industry_type: components["schemas"]["IndustryType"];
            /** Contact Id */
            contact_id: number;
        };
        /** IndustryOpt */
        IndustryOpt: {
            /** Pk */
            pk: number;
            industry_type: components["schemas"]["IndustryType"];
        };
        /**
         * IndustryType
         * @enum {string}
         */
        IndustryType: "Agriculture, Forestry, and Fishing" | "Mining and Quarrying" | "Manufacturing" | "Utilities (Electricity, Gas, and Water Supply)" | "Water Supply, Waste Management, and Remediation" | "Construction" | "Wholesale and Retail Trade" | "Transportation and Storage" | "Accommodation and Food Service Activities" | "Information and Communication" | "Financial and Insurance Activities" | "Real Estate Activities" | "Professional, Scientific, and Technical Services" | "Administrative and Support Services" | "Public Administration and Defense" | "Education" | "Human Health and Social Work Activities" | "Arts, Entertainment, and Recreation" | "Other Service Activities" | "Activities of Households as Employers" | "Activities of Extraterritorial Organizations";
        /** IndustryUpdate */
        IndustryUpdate: {
            industry_type: components["schemas"]["IndustryType"];
        };
        /** PaginatedAddress */
        PaginatedAddress: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["Address"][];
        };
        /** PaginatedAddressOpt */
        PaginatedAddressOpt: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["AddressOpt"][];
        };
        /** PaginatedContact */
        PaginatedContact: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["Contact"][];
        };
        /** PaginatedContactOpt */
        PaginatedContactOpt: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["ContactOpt"][];
        };
        /** PaginatedCountry */
        PaginatedCountry: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["Country"][];
        };
        /** PaginatedCountryOpt */
        PaginatedCountryOpt: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["CountryOpt"][];
        };
        /** PaginatedCurrency */
        PaginatedCurrency: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["Currency"][];
        };
        /** PaginatedCurrencyOpt */
        PaginatedCurrencyOpt: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["CurrencyOpt"][];
        };
        /** PaginatedIndustry */
        PaginatedIndustry: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["Industry"][];
        };
        /** PaginatedIndustryOpt */
        PaginatedIndustryOpt: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["IndustryOpt"][];
        };
        /** PaginatedPhoneCode */
        PaginatedPhoneCode: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["PhoneCode"][];
        };
        /** PaginatedPhoneCodeOpt */
        PaginatedPhoneCodeOpt: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["PhoneCodeOpt"][];
        };
        /** PaginatedTag */
        PaginatedTag: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["Tag"][];
        };
        /** PaginatedTagOpt */
        PaginatedTagOpt: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["TagOpt"][];
        };
        /** PaginatedUpload */
        PaginatedUpload: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["Upload"][];
        };
        /** PaginatedUploadDataError */
        PaginatedUploadDataError: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["UploadDataError"][];
        };
        /** PaginatedVAT */
        PaginatedVAT: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["VAT"][];
        };
        /** PaginatedVATOpt */
        PaginatedVATOpt: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["VATOpt"][];
        };
        /** PhoneCode */
        PhoneCode: {
            /** Pk */
            pk: number;
            country: components["schemas"]["Country"] | null;
            /** Phone Code */
            phone_code: string;
        };
        /** PhoneCodeOpt */
        PhoneCodeOpt: {
            /** Pk */
            pk: number;
            country: components["schemas"]["Country"] | null;
            /** Phone Code */
            phone_code: string;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "Queued" | "Running" | "Success" | "Failed" | "Cancelling" | "Cancelled" | "Stopping" | "Stopped" | "Timeout" | "Unknown";
        /** Tag */
        Tag: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Modified At
             * Format: date-time
             */
            last_modified_at: string;
            created_by: components["schemas"]["UserMin"];
            last_modified_by: components["schemas"]["UserMin"] | null;
        };
        /** TagCreate */
        TagCreate: {
            /** Name */
            name: string;
        };
        /** TagMin */
        TagMin: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
        };
        /** TagOpt */
        TagOpt: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
        };
        /** TagUpdate */
        TagUpdate: {
            /** Name */
            name: string;
        };
        /** TaskMin */
        TaskMin: {
            /** Pk */
            pk: number;
            status: components["schemas"]["Status"];
            /** Message */
            message: string | null;
            /** Progress */
            progress: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
        };
        /** Upload */
        Upload: {
            /** Pk */
            pk: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Modified At
             * Format: date-time
             */
            last_modified_at: string;
            created_by: components["schemas"]["UserMin"];
            last_modified_by: components["schemas"]["UserMin"] | null;
            task: components["schemas"]["TaskMin"];
        };
        /** UploadDataError */
        UploadDataError: {
            /** Pk */
            pk: number;
            /** Sheet */
            sheet: string;
            /** Row */
            row: number;
            /** Column */
            column: string;
            /** Error */
            error: string;
        };
        /** UserImageURL */
        UserImageURL: {
            /** Url */
            url: string | null;
        };
        /** UserMin */
        UserMin: {
            /** Pk */
            pk: number;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            image: components["schemas"]["UserImageURL"];
        };
        /** VAT */
        VAT: {
            /** Pk */
            pk: number;
            country: components["schemas"]["Country"] | null;
            /** Name */
            name: string;
            /** Rate */
            rate: number;
        };
        /** VATOpt */
        VATOpt: {
            /** Pk */
            pk: number;
            country: components["schemas"]["Country"] | null;
            /** Name */
            name: string;
            /** Rate */
            rate: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_contact_contact__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                name?: string | null;
                name__icontains?: string | null;
                parent_id?: number | null;
                legal_type?: components["schemas"]["ContactLegalType"] | null;
                deleted_at__isnull?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedContact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_contact_contact__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_contact_contact__contact_id___get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contact_contact__contact_id___put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_contact_contact__contact_id___delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_contact_option_options_contact__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                name?: string | null;
                name__icontains?: string | null;
                parent_id?: number | null;
                legal_type?: components["schemas"]["ContactLegalType"] | null;
                deleted_at__isnull?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedContactOpt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    soft_delete_contact_contact__contact_id__soft_delete_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_contact_image_contact__contact_id__image__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_contact_image_contact__contact_id__image__put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_contact_image_contact__contact_id__image__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_contact_upload_template_contact_upload_template__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_contact_upload_contact_upload__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUpload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_contact_contact_upload__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_contact_contact_upload__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_contact_upload_contact_upload__upload_id___get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_contact_upload_contact_upload__upload_id___delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_contact_upload_data_error_contact_upload__upload_id__data_error__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                sheet?: string | null;
            };
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUploadDataError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_industry_industry__get: {
        parameters: {
            query: {
                page?: number;
                page_size?: number;
                contact_id: number;
                industry_type?: components["schemas"]["IndustryType"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedIndustry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_industry_industry__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndustryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Industry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_industry_industry__industry_id___get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                industry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Industry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_industry_industry__industry_id___put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                industry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndustryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Industry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_industry_industry__industry_id___delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                industry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_industry_option_options_industry__get: {
        parameters: {
            query: {
                page?: number;
                page_size?: number;
                contact_id: number;
                industry_type?: components["schemas"]["IndustryType"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedIndustryOpt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_address_address__get: {
        parameters: {
            query: {
                page?: number;
                page_size?: number;
                contact_id: number;
                address_type?: components["schemas"]["AddressType"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAddress"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_address_address__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Address"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_address_address__address_id___get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Address"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_address_address__address_id___put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Address"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_address_address__address_id___delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_address_option_options_address__get: {
        parameters: {
            query: {
                page?: number;
                page_size?: number;
                contact_id: number;
                address_type?: components["schemas"]["AddressType"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAddressOpt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_country_country__country_id___get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                country_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Country"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_country_country__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                name?: string | null;
                iso_a2?: string | null;
                iso_a3?: string | null;
                iso_n?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCountry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_country_option_options_country__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                name?: string | null;
                iso_a2?: string | null;
                iso_a3?: string | null;
                iso_n?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCountryOpt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_currency_currency__currency_id___get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                currency_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Currency"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_currency_currency__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                country_id?: number | null;
                name?: string | null;
                iso?: string | null;
                symbol?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCurrency"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_currency_option_options_currency__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                country_id?: number | null;
                name?: string | null;
                iso?: string | null;
                symbol?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCurrencyOpt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_phonecode_phonecode__phonecode_id___get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                phonecode_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneCode"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_phonecode_phonecode__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                country_id?: number | null;
                phone_code?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPhoneCode"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_phonecode_option_options_phonecode__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                country_id?: number | null;
                phone_code?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPhoneCodeOpt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_vat_vat__vat_id___get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VAT"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vat_vat__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                country_id?: number | null;
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedVAT"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vat_option_options_vat__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                country_id?: number | null;
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedVATOpt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tag_tag__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tag_tag__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tag_option_options_tag__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                name?: string | null;
                name__icontains?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTagOpt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tag_tag__tag_id___put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tag_tag__tag_id___delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
