/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/product/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Product */
        get: operations["list_product_product__get"];
        put?: never;
        /** Create Product */
        post: operations["create_product_product__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/{product_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Product */
        get: operations["retrieve_product_product__product_id___get"];
        /** Update Product */
        put: operations["update_product_product__product_id___put"];
        post?: never;
        /** Delete Product */
        delete: operations["delete_product_product__product_id___delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/options/product/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Product Option */
        get: operations["list_product_option_options_product__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/{product_id}/stock/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Product Stock */
        put: operations["update_product_stock_product__product_id__stock__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/{product_id}/image/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload Product Image */
        put: operations["upload_product_image_product__product_id__image__put"];
        post?: never;
        /** Delete Product Image */
        delete: operations["delete_product_image_product__product_id__image__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product_category/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Product Category */
        get: operations["list_product_category_product_category__get"];
        put?: never;
        /** Create Product Category */
        post: operations["create_product_category_product_category__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product_category/{product_category_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Product Category */
        get: operations["retrieve_product_category_product_category__product_category_id___get"];
        /** Update Product Category */
        put: operations["update_product_category_product_category__product_category_id___put"];
        post?: never;
        /** Delete Product Category */
        delete: operations["delete_product_category_product_category__product_category_id___delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/options/product_category/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Product Category Option */
        get: operations["list_product_category_option_options_product_category__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountMin */
        AccountMin: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
            /** Number */
            number: string;
            account_type: components["schemas"]["AccountType"] | null;
            /** Account Number */
            account_number: string;
        };
        /**
         * AccountType
         * @enum {string}
         */
        AccountType: "Asset" | "Liability" | "Equity" | "Revenue" | "Expense";
        /** Body_upload_product_image_product__product_id__image__put */
        Body_upload_product_image_product__product_id__image__put: {
            /**
             * Upload
             * Format: binary
             */
            upload: string;
        };
        /** CurrencyMin */
        CurrencyMin: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
            /** Iso */
            iso: string;
            /** Symbol */
            symbol: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PaginatedProduct */
        PaginatedProduct: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["Product"][];
        };
        /** PaginatedProductCategory */
        PaginatedProductCategory: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["ProductCategory"][];
        };
        /** PaginatedProductCategoryOpt */
        PaginatedProductCategoryOpt: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["ProductCategoryOpt"][];
        };
        /** PaginatedProductOpt */
        PaginatedProductOpt: {
            /** Total Items */
            total_items: number;
            /** Total Page */
            total_page: number;
            /** Page */
            page: number;
            /** Items */
            items: components["schemas"]["ProductOpt"][];
        };
        /** Product */
        Product: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
            /** Price */
            price: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Modified At
             * Format: date-time
             */
            last_modified_at: string;
            created_by: components["schemas"]["UserMin"];
            last_modified_by: components["schemas"]["UserMin"] | null;
            product_type: components["schemas"]["ProductType"];
            unit: components["schemas"]["Unit"];
            /** Stock */
            stock: string;
            income_account: components["schemas"]["AccountMin"] | null;
            expense_account: components["schemas"]["AccountMin"] | null;
            image: components["schemas"]["ProductImageURL"];
            product_category: components["schemas"]["ProductCategoryMin"];
            currency: components["schemas"]["CurrencyMin"];
            /** Tags */
            tags: components["schemas"]["TagMin"][];
        };
        /** ProductCategory */
        ProductCategory: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
            income_account: components["schemas"]["AccountMin"];
            expense_account: components["schemas"]["AccountMin"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Modified At
             * Format: date-time
             */
            last_modified_at: string;
            created_by: components["schemas"]["UserMin"];
            last_modified_by: components["schemas"]["UserMin"] | null;
        };
        /** ProductCategoryCreate */
        ProductCategoryCreate: {
            /** Name */
            name: string;
            /** Income Account Id */
            income_account_id: number;
            /** Expense Account Id */
            expense_account_id: number;
        };
        /** ProductCategoryMin */
        ProductCategoryMin: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
        };
        /** ProductCategoryOpt */
        ProductCategoryOpt: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
        };
        /** ProductCategoryUpdate */
        ProductCategoryUpdate: {
            /** Name */
            name: string;
            /** Income Account Id */
            income_account_id: number;
            /** Expense Account Id */
            expense_account_id: number;
        };
        /** ProductCreate */
        ProductCreate: {
            /** Name */
            name: string;
            /** Price */
            price: number | string | null;
            product_type: components["schemas"]["ProductType"];
            unit: components["schemas"]["Unit"];
            /** Currency Id */
            currency_id: number;
            /** Product Category Id */
            product_category_id: number;
            /** Income Account Id */
            income_account_id: number | null;
            /** Expense Account Id */
            expense_account_id: number | null;
            /** Tags */
            tags: number[];
        };
        /** ProductImageURL */
        ProductImageURL: {
            /** Url */
            url: string | null;
        };
        /** ProductOpt */
        ProductOpt: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
            /** Price */
            price: string | null;
            unit: components["schemas"]["Unit"];
            /** Stock */
            stock: string;
            image: components["schemas"]["ProductImageURL"];
        };
        /** ProductStockUpdate */
        ProductStockUpdate: {
            /** Stock */
            stock: number | string;
        };
        /**
         * ProductType
         * @enum {string}
         */
        ProductType: "Goods" | "Service";
        /** ProductUpdate */
        ProductUpdate: {
            /** Name */
            name: string;
            /** Price */
            price: number | string | null;
            unit: components["schemas"]["Unit"];
            /** Currency Id */
            currency_id: number;
            /** Product Category Id */
            product_category_id: number;
            /** Income Account Id */
            income_account_id: number | null;
            /** Expense Account Id */
            expense_account_id: number | null;
            /** Tags */
            tags: number[];
        };
        /** TagMin */
        TagMin: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
        };
        /**
         * Unit
         * @enum {string}
         */
        Unit: "Piece" | "Kg" | "Litre" | "Meter" | "Square Meter" | "Cubic Meter" | "Box" | "Bag" | "Bottle" | "Can" | "Tube" | "Roll" | "Set" | "Pair" | "Dozen" | "Pack" | "Ream" | "Bundle" | "Kit" | "Unit" | "Other" | "Unknown" | "Custom";
        /** UserImageURL */
        UserImageURL: {
            /** Url */
            url: string | null;
        };
        /** UserMin */
        UserMin: {
            /** Pk */
            pk: number;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            image: components["schemas"]["UserImageURL"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_product_product__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                name?: string | null;
                name__icontains?: string | null;
                product_type?: components["schemas"]["ProductType"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProduct"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_product__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_product_product__product_id___get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_product__product_id___put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_product__product_id___delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_product_option_options_product__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                name?: string | null;
                name__icontains?: string | null;
                product_type?: components["schemas"]["ProductType"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProductOpt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_stock_product__product_id__stock__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductStockUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_product_image_product__product_id__image__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_product_image_product__product_id__image__put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_image_product__product_id__image__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_product_category_product_category__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProductCategory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_category_product_category__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductCategory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_product_category_product_category__product_category_id___get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductCategory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_category_product_category__product_category_id___put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCategoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductCategory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_category_product_category__product_category_id___delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_product_category_option_options_product_category__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProductCategoryOpt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
